
# Add labels the plugin from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Shape features extraction
  - Object feature extraction
  - Object characteristics
  - Object shape
  - Intensity
  - Region properties
  - Spatial properties
  - Statistics
